### ISSUE TITLE
Add rumor manager user role

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#168]

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 is "RumMan" ok as abreviation? Or better "RumoMan"

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda I prefer the first option

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 What do you think about calling this role "Alert Supervisor"? This would be a better fit with the events that are now called Alerts. Just an idea, but I'm not sure how this maps to the real world roles.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda In the real world they are known as Rumor Manager at the regional level (state level) and since we have already established a persona label called Rumour officer/manager in our sormas system, i think we should still retain it. You can also refer to the events as "Alert Events" to differentiate from just Events

**Comment by MartinWahnschaffeSymeda** [comment]
Ok, we keep Rumor Manager
