### ISSUE TITLE
All communication between app and server is authenticated with the user's credentials [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#180]
Depends on #202 

- [x] use basic auth to secure transactions on server side
- [x] use basic auth to secure transactions on app side
- [x] use provided user login to authentication
- [x] handle 401 and other possible errors
- [x] give only offiers and informants access to the rest interface

### When (not) to Use OAuth2
You should only use OAuth if you actually need it. If you are building a service where you need to use a user’s private data that is stored on another system — use OAuth. If not — you might want to rethink your approach!
Don’t Use OAuth2 for Sensitive Data. If you’re building an application that holds sensitive data (like social security numbers, etc.) — consider using OAuth 1.0a instead of OAuth2 — it’s much more secure.
There are other forms of authentication for both websites and API services that don’t require as much complexity, and can offer similar levels of protection in certain cases.
Namely: HTTP Basic Authentication and HTTP Digest Authentication.
source: https://stormpath.com/blog/what-the-heck-is-oauth
### OAuth2 introductions & examples
* intro to oauth2: https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2
* Spring REST API + OAuth2 + AngularJS: http://www.baeldung.com/rest-api-spring-oauth2-angularjs
* Android OAuth2 with AccountManager & Retrofit: https://gist.github.com/burgalon/dd289d54098068701aee
### Using basic auth vs. digest auth
Use digest auth only when it's not possible to force SSL
source: http://mark-kirby.co.uk/2013/how-to-authenticate-apis-http-basic-vs-http-digest/
### Things to deal with when using basic auth
1. In order to use the service, the client needs to keep the password somewhere in clear text to send it along with each request.
2. The verification of a password should be very slow (to counter brute force attacks), which would hamper scalability of your service. On the other hand, security token validation can be quick 
source: http://softwareengineering.stackexchange.com/questions/290511/auth-options-for-distributed-systems/291030#291030

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda It is important that the users can authenticate their login session with a 4 digit pin after registering the username and password the first time. it wont be user frinedly to keep entering that 8 or 9 alpha numeric password as we currently have. Also we need to think about when they forget their password, what is the best way to do it without always informing the supervisor to change it for them. This is part of security safety because they are responsible for whatever happens on their accoutn as we will track all user activities within the system. So even the supervisor should not know what their passwords are.

**Comment by MartinWahnschaffeSymeda** [comment]
First steps are done. Authentication problems still need to be handled
