### ISSUE TITLE
Map View

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#186]
1. Relayout the dashboard:

- [x] put the situation report on the left
- [x] map on top right (much smaller)
- [x] epi curve on bottom right
- [x] add info about onset date to the date filters

2. Map view

- [x] add a new view with the map only (and filters)
- [x] add a link to the small map on the dashboard

**Comment by MateStrysewskeSym** [comment]
I've chosen a different approach to this issue; the map is on the left side (purely a design choice because the whole page looked bad with the report table on the left and the map on the top right), the epi curve on the top right and the table on the bottom right; instead of adding a new page that shows a large map, I've added an expand/collapse button that toggles the visibility of all other components and adjusts the map size.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] experiment with other layout

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Hi Martin, As we have begun the next phase, I just observed one little aspect that would need to be added before we can deploy in July. It is the EPI Week field. All Nigerian Epi curves are not based on date of onset only as we were informed during the testing workshop but also by epi weeks. This is specifically for adding a new field called Epi weeks to define what week a case was detected. Please lets keep this in mind! Thanks
