### ISSUE TITLE
App Exception Handling Refactoring [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#187]
- [x] prepare exception handling refactoring: which types of exceptions are we using. What needs to be replaced?
- [x] backend methods should throw dedicated exceptions instead of RuntimeExceptions (add throws to DAO method signatures)
- [x] inform users about caught exceptions (via toasts)
- [x] log exceptions and find out which the preferred method is for Android
- [x] find a way to collect exceptions thrown during the performance of asynchronous tasks (i.e. synchronization) and to show them to the user and send them to analytics
- [x] check what happens when trying to synchronize in offline mode

**Comment by MateStrysewskeSym** [comment]
We still need to find a way to display errors during the synchronization process (this actually always happens when the user is offline) occur; however, this should probably only happen when the user manually refreshes a list (because otherwise they'll be spammed with a lot of error messages), and only once and not for every entity that couldn't be synchronized.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] turn hasThrownError to an instance field
