### ISSUE TITLE
"First symptom" field shows validation error although filled

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#260]
To reproduce: Set symptoms "fever" and "vomitting" to yes. The first symptom field will be prefilled with "fever". Saving now doesn't work.

- [x] Fix not being able to save when the onset symptom is set to the first selected symptom automatically
- [x] Fix entries appearing multiple times in the list after using the "Clear all" button

**Comment by MateStrysewskeSym** [comment]
The issue with entries appearing multiple times in the list is very likely caused by an Android bug that causes a RadioGroup button to be called twice, once with the current value and once with the new one (-1) when using clearCheck(), see https://issuetracker.google.com/issues/36910520. A workaround for this problem has been implemented.
