### ISSUE TITLE
Contact & case map refinements

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#351]
- [x] same for cases (end/outcome does not exist yet)
- [x] use address gps of the contact if no visit gps exists
- [x] split "show contacts" into "show confirmed contacts" and "show unconfirmed contacts" or add contact status filter combo box
- [ ] ~~use date interval from date of contact report until end of follow-up for time filtering~~
- [ ] ~~for contacts that have been visited use the geo coordinated of the last visit instead of the report geo coordinates~~

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 For the contact map: We suggest to use the time interval from date of contact report until end of follow-up to filter the contact maps when a time interval filter is active. Do you think this is correct?

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] contact date filter is based on the associated case's date of onset or date or report

**Comment by MateStrysewskeSym** [comment]
@dta16 Which coordinates should we use to display the contacts on the map? Should it be the report coordinates of the last cooperative visit? Or the report coordinate of the contact?

**Comment by dta16** [comment]
The report coordinates of the contact

On Nov 8, 2017 4:46 PM, "MateStrysewskeSym" <notifications@github.com>
wrote:

@dta16 <https://github.com/dta16> Which coordinates should we use to
display the contacts on the map? Should it be the report coordinates of the
last cooperative visit? Or the report coordinate of the contact?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hzi-braunschweig/SORMAS-Open/issues/351#issuecomment-342858408>,
or mute the thread

**Comment by MateStrysewskeSym** [comment]
- [ ] fix exception when calling getContactsForMap with empty case list
- [ ] add join call to case uuid instead of getting all cases in FacadeEjb
