### ISSUE TITLE
New Dashboard for Surveillance Supervisor

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#355]
== General
- [x] Filter all querries by selected district
- [x] Filter by onset date or week (add year to week)
- [x] remove date subheadlines for statistics components
- [x] make sure that graphics are displayed for national user
- [x] find a way to make all statistics component same height

== New Cases
- [x] Total, confirmed, probable, suspected based on the onset filter
- [x] Show total for all diseases that have or had cases

== My Tasks
- [x] high, normal, low
- [x] total, pending, overdue, done, .. (see filtered)
- [x] show all pending tasks and only done, removed and not executable tasks with a status change date in the current epi week

== New Alerts
- [x] As in mockup

== New Test Results
- [x] numbers as in mockup, use "positive"/"negative" or "POS"/"NEG" instead of "+VE"/"-VE"
- [x] grouped by disease: show only positive tests
- [x] district filtered: show shipped status

== Curve & Map
- [x] Adjust layout based on mockup
- [x] Add "Alive or Dead" option for epi curve

[SORMAS Mockup 1920x1080 Dashboard Surveillance Supervisor - All v15.pdf](https://github.com/hzi-braunschweig/SORMAS-Open/files/1371838/SORMAS.Mockup.1920x1080.Dashboard.Surveillance.Supervisor.-.All.v15.pdf)
[SORMAS Mockup 1920x1080 Dashboard Surveillance Supervisor - Filtered v5.pdf](https://github.com/hzi-braunschweig/SORMAS-Open/files/1371839/SORMAS.Mockup.1920x1080.Dashboard.Surveillance.Supervisor.-.Filtered.v5.pdf)

**Comment by MartinWahnschaffeSymeda** [comment]
Addition:

- [ ] dashboard map filters (district, disease, date): switch on by default

**Comment by MartinWahnschaffeSymeda** [comment]
From the review:

- [ ] remove dependency on DashboardView in EpiCurve- and MapComponent (e.g. addExpandListener will make the expand button visible and let an outside component handle the event).

**Comment by MateStrysewskeSym** [comment]
@dta16 "New cases", "New events" and "New test results" are all filtered by disease, if one is selected. I recommend not filtering the tasks at all because they should always give a general overview to the user how many tasks they still have to do and how many they've done.

However, it's currently unclear to me which tasks exactly should be shown to the user. I suggest to not show (as in displaying the number of) all done, not executable and removed tasks, because tasks that have been completed months ago are hardly relevant for an overview. Concerning pending tasks, should we show the number of ALL pending tasks, no matter their due date, or only the number of tasks that are due THIS exact epi week?

I suggest to do the following:

- show ALL pending tasks or only those that are due this epi week (please write down your preferred option)
- show only those done, not executable and removed tasks that are due this epi week

If we only show the number of pending tasks that are due this week, this will result in a more gamification-like scenario where, at the end of the week, the user should have an overview that shows all tasks as done and none as pending. If we show all pending tasks irrespective of due date, this might not happen as frequently, but might give a better overview to the user on how many pending tasks they have in total, even if they don't have to approach all of them in this week.

**Comment by dta16** [comment]
I totally agree with this approach Mate. Please go ahead.

Thanks

**Comment by MateStrysewskeSym** [comment]
@dta16 Okay, I've now chosen the first option (displaying done/not executable/removed tasks only for the current week).

**Comment by MartinWahnschaffeSymeda** [comment]
Performance in chrome was bad due to layouting problems with the vertical separator label.

- [ ] find an alternative solution
