### ISSUE TITLE
Match or pick person not working. 

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#390]
@dta16 Is is not working for the app or the website? Can you describe what exactly is not working?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda 
We have issues whereby people are entering retrospective cases and contacts and hence, creating persons within SORMAS who are already suspected cases but were contacts to a source case. The officers are misguided to first create these contacts who have become symptomatic as primary cases and then when they try to add these contacts (instead of first of all creating case as contact and converting to case), and "pick matching person" when you try to create a case as a contact does not allow the officer to match persons but forces the officer to create person as a new person. Please let the system allow contacts who were already cases before entering SORMAS to be added as contacts to the shource case. This is also related to the source tracing. Is this clear?

**Comment by MartinWahnschaffeSymeda** [comment]
Problem: selected person in table is not visualized

**Comment by MartinWahnschaffeSymeda** [comment]
This is working now. There is still a lot of other stuff to be considered - see #402
