### ISSUE TITLE
Contact Officer should not see the cases, events and samples list in the menu

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#398]
Adjust the visible menu entries

- [x] only contact officer should have contacts list
- [x] only case officer, surveillance officer and informant should have cases, samples and event list
- [x] weekly reports is only visible to informant and surveillance officer

all users have the task list.

@dta16 Is this correct?

**Comment by dta16** [comment]
Yes


On Nov 9, 2017 14:33, "Martin Wahnschaffe" <notifications@github.com> wrote:

Adjust the visible menu entries

   - only contact officer should have contacts list
   - only case officer, surveillance officer and informant should have
   cases, samples and event list
   - weekly reports is only visible to informant and surveillance officer

all users have the task list.

@dta16 <https://github.com/dta16> Is this correct?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hzi-braunschweig/SORMAS-Open/issues/398>, or mute the
thread
