### ISSUE TITLE
Case ID WMKGYH dropped from user view - sub-list sync problem

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#403]
@MartinWahnschaffeSymeda 
Synchronization conflicts: Changes dropped because officer has no longer access to this entity

Solve: Android studio install and retrieve file.

Reason for problem: unknown

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 I was able to reproduce this and it goes down to a bug that will drop unsynchronized data even when it was never synced at all.

We will fix this immediately, but the case data is most likely lost.

In addition to this we have to implement #399 and #400 for the following release in order to have a backup for such situations.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] find cause of sync error

**Comment by MartinWahnschaffeSymeda** [comment]
DaoException - Root cause: java.lang.NullPointerException: null receiver - Stack trace: de.symeda.sormas.app.backend.common.AdoDtoHelper:pullEntities:83 -> de.symeda.sormas.app.backend.common.AdoDtoHelper:pullAndPushEntities:57 -> de.symeda.sormas.app.rest.SynchronizeDataAsync:synchronizeChangedData:136 -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:73 -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:103 -> de.symeda.sormas.app.rest.SynchronizeDataAsync$2:doInBackground:267 -> android.os.AsyncTask$2:call:304 -> java.util.concurrent.FutureTask:run:237 -> android.os.AsyncTask$SerialExecutor$1:run:243 -> java.util.concurrent.ThreadPoolExecutor:runWorker:1133 -> java.util.concurrent.ThreadPoolExecutor$Worker:run:607 -> java.lang.Thread:run:761 - Root cause stack trace: java.lang.reflect.Method:invoke:-2 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:mergeOrCreate:559 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:mergeOrCreateWithCast:466 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:mergeCollection:683 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:mergeOrCreate:632 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:mergeOrCreateWithCast:466 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:mergeOrCreate:540 -> de.symeda.sormas.app.backend.caze.CaseDao:mergeOrCreate:263 -> de.symeda.sormas.app.backend.caze.CaseDao:mergeOrCreate:46 -> de.symeda.sormas.app.backend.common.AdoDtoHelper$1:call:100 -> de.symeda.sormas.app.backend.common.AdoDtoHelper$1:call:95 -> com.j256.ormlite.misc.TransactionManager:callInTransaction:168 -> com.j256.ormlite.stmt.StatementExecutor:callBatchTasks:553 -> com.j256.ormlite.dao.BaseDaoImpl:callBatchTasks:633 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:callBatchTasks:1036 -> de.symeda.sormas.app.backend.common.AdoDtoHelper:handlePullResponse:95 -> de.symeda.sormas.app.backend.common.AdoDtoHelper:pullEntities:79 -> de.symeda.sormas.app.backend.common.AdoDtoHelper:pullAndPushEntities:57 -> de.symeda.sormas.app.rest.SynchronizeDataAsync:synchronizeChangedData:136 -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:73 -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:103 -> de.symeda.sormas.app.rest.SynchronizeDataAsync$2:doInBackground:267 -> android.os.AsyncTask$2:call:304 -> java.util.concurrent.FutureTask:run:237 -> android.os.AsyncTask$SerialExecutor$1:run:243 -> java.util.concurrent.ThreadPoolExecutor:runWorker:1133 -> java.util.concurrent.ThreadPoolExecutor$Worker:run:607 -> java.lang.Thread:run:761 - User: TL56AZ-ZW56TE-P5YKKL-NCNLKGHQ

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 We will need the mobile database to be able to investigate on the problem

**Comment by MartinWahnschaffeSymeda** [comment]
I was able to reproduce this. It happens when a sub-list (e.g. previous hospitalizations) is changed at the same time on server and mobile device. The sync mechanism has a bug in this situation.
