### ISSUE TITLE
Hospital Informant Health facility entry empty. 

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#427]
Error. Informant while creating a case cannot proceed because health facility field empty
![img-20171125-wa0026](https://user-images.githubusercontent.com/19344651/33230404-0df3dc74-d1e3-11e7-8c36-7e8fbdb072ec.jpg)

**Comment by hzi-braunschweig** [comment]
![img-20171126-wa0002](https://user-images.githubusercontent.com/19344651/33239565-b7c43e8a-d2a4-11e7-91af-e0d15fd1ff33.jpg)
We still have this null errors. We officially cannot create cases as hospital informants. @MartinWahnschaffeSymeda @MateStrysewskeSym

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 Found the problem. This happens, when the initial sync is canceled or failes due to bad internet connection while retrieving the health facilities.

You can workarround it by clearing the data of the android app and syncing again.

We will create a fix for this problem today and deliver the new version this evening.

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 The missing health facilities should correctly be synced in the new version.
It's likely that there is missing data on the device that could not be loaded due to missing health facilities before (e.g. contacts).

In the settings screen, there is a "re-synchronize data" button. Hit this button once, on devices that had problem with the health facilities.
