### ISSUE TITLE
Filter by reporting user and not only responsible user [0.5]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#442]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
Please we need to urgently filter by reporting user to enable us separate data entered from the field and data entered from the EOC. 

Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 
I suppose this is needed for cases.
For anything else as well?

**Comment by dta16** [comment]
For contacts and events as well. Therr is alot of data coming in from the
field and from the national level and i want to bulk select all national
level users to exclude their sata entered to know exactly what data is
being entered from the field. The only variable that can do this is the
reporting user

Thanks

On Dec 7, 2017 14:20, "Martin Wahnschaffe" <notifications@github.com> wrote:

@dta16 <https://github.com/dta16>
I suppose this is needed for cases.
For anything else as well?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hzi-braunschweig/SORMAS-Open/issues/442#issuecomment-349964681>,
or mute the thread

**Comment by MartinWahnschaffeSymeda** [comment]
Ok, we will add a filter by user role then.

**Comment by MateStrysewskeSym** [comment]
- [ ] allow filtering by reporting user role
- [ ] implement in backend (instead of container filter)

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym I have introduced the CaseCriteria. I suggest to use this as a general pattern for all mayor entities. 
I will go on with the implementation once #294 is done.
