### ISSUE TITLE
Auto update of app on device without uninstalling old version [0,5]

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Open#500]
Can we have auto update of app's new versions without uninstalling the existing app on the device?

**Comment by MartinWahnschaffeSymeda** [comment]
We will look into this. If I get you right the problem is as follows:
You are trying to install a new version on a device, but it doesn't work and you have to uninstall the old version first. Right?

How was the old version installed? Manually or via MDM?
How is the new version installed? Manually or via MDM?

**Comment by Chinedar** [comment]
Both apps we're installed manually. Once we confirm by reason of test, that
MDM can push updates then am sure the problem would be solved.

Thanks!

On Feb 5, 2018 17:54, "Martin Wahnschaffe" <notifications@github.com> wrote:

We will look into this. If I get you right the problem is as follows:
You are trying to install a new version on a device, but it doesn't work
and you have to uninstall the old version first. Right?

How was the old version installed? Manually or via MDM?
How is the new version installed? Manually or via MDM?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hzi-braunschweig/SORMAS-Open/issues/500#issuecomment-363146907>,
or mute the thread

**Comment by MateStrysewskeSym** [comment]
- [ ] reproduce the problem

Might be related to missing apk signature.

**Comment by MartinWahnschaffeSymeda** [comment]
Reproduced the problem using app from release 0.12.1 then 0.13.1.

Goes down to the debug signature:
"The problem is the keys that have been used to sign the APKs, by default if you are running directly from your IDE and opening your Emulator, the APK installed in the Emulator is signed with your debug-key(usually installed in ~/.android/debug.keystore), so if the previous APK was signed with a different key other than the one you are currently using you will always get the signatures conflict, in order to fix it, make sure you are using the very same key to sign both APKs, even if the previous APK was signed with a debug-key from another SDK, the keys will definitely be different."
https://stackoverflow.com/questions/19959890/android-app-not-install-an-existing-package-by-the-same-name-with-a-conflicting

-> #246
