### ISSUE TITLE
Search cases by date range [2]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Open#510]
In the case folder, I can't view ONLY monkeypox cases reported from January 2018 till today;  We have to program it as on the dash board.
Goal: To be able to search casses in an interval of time in the cases directory.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] add from, to, epi-week/date filters. add description to let users know that 
- [ ] add same info as used on dashboard (and add reception date)
- [ ] move vaadin logic into helper method or so

@hzi-braunschweig 
Since we have too many filters in the view now, we suggest to add another line that is collapsed by default and can be shown by clicking an "more filters" button.
The following filters would be in this hidden line: present condition, LGA, facility, reported by, from/to date filter.
Is this ok?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda  I am fine with this. I think the collapsed drawer with more filter is a goo didea. 


Thanks
