### ISSUE TITLE
Import existing cases via CSV [13]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#512]
3 points about what we need for SORMAS:

1. SORMAS should be able to import or export data (currently ongoing,, expected next release)

2. As national level user, they should be able to stratify dashboard and view by state, also statistics to be stratified by states

Dear Wunmi
1.	We have put the import export function of SORMAS as a priority and this will  be in the next version that you guys will get
2.	As for the national level to view dashboard by state, currently it works only if you are a user of that state. However, I asked Ferdinand to add that to the github development platform and we will try to work on this asap to stratify statistics also by States. 
3.	As for adding new health facilities, we have that already which should not stop them doing their work. They can use the function “other health facilities’ where they don’t see the health facilities in the dropdown. Here new health facilities can be added to SORMAS. 

@MartinWahnschaffeSymeda  This mail was sent today by me to the Nigeria team. They need these items for the next release version. We can talk on the phone if you have questions. 

Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
* Export is done here #507 
* for health facility adding see #514 
* for dashboard filter see #513 

@hzi-braunschweig 
For the import feature we need some example files on what should be importable.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda This needs some more thinking around it. But for now, see below MPX example from their linelist
Epid No
Patient Name
Nickname
Date of birth
Age
Gender
State
LGA
Village of   residence
Neighborhood
Nationality
Occupation
SpecifyforHWorOtheroccupation
Reception Date
Date of   investigation
Case Reporter   by
Number or Name   of HF
Form completed   by
Information   given by
Relationship   with the patient
Dateofonset
Patient Status
If dead, Date   of Death
If death,   Place of death
If death,   Country of death
Smallpox   vaccination
Rash
Date of rash   onset
Epi-Week
Village where   the patient developed the rash
Country where   the patient developed the rash
Fever
Date of fever   onset
Fever precede   the rash
Lesions same   development state
Lesions with   same size
Lesions deep   and profound
Lesion on Face
Lesions on   Legs
Lesions   onThorax
Lesions on   Arms
Lesions on   Soles of feet
Lesions on   Genitals
Lesions on   Palms
Vomiting or   nausea
Cough
Lymphadenopathy
Lymphadenopathy   inguinal
Lymphadenopathy   axillary
Lymphadenopathy   cervical
Chills or   sweats
Sore throat
Oral ulcers
Headache
Lesions that   itch
Myalgia
8Fatigue
Sensitivity to   light
Conjunctivitis
Bedridden
Travel History   before illness
Place of   Travel before illness
Travel during   the illness
Place Travel   during illness
Contact With   symptomatic person
Contact person   name
Contact Pesron   Relationship
Date of   contact with sick Person
Family contact   with sick person
Prepared food   together with sick person
Shared a bed   with sick person
Took care of   this sick person
School Friend
Met at   themarket with the sick person
Hunted   together with sick person
Friend with   sick person
Met the sick   person at church
Other   information about the symptomatic contact person
Animal Contact
Kind of animal
Date of Animal   contact
Contact with   an aliv animal forest?
Contact with   rodents alive in the house?
Contact with   animal bought for meat?
Contact with a   dead forest animal?
Date of fever   onset
Date of rash   onset
Specimen   collected
Specimen   collection date
Crust?
Swab?
Blood?
Hospitalisation
Hospitalisation   date
Isolation
Date of   discharge
OUTCOME
Finalclassification
Comments
Lab confirmed   diff diagnosis
Additional   contacts
Fisrt   additional contact name
Relationship   with first addional contact
Date of   contact with first additional contact
Q46Familycontact2
Q46Preparedfoodtogether2
Q46Sharedabed2
Q46Tookcareofthissickperson2
Q46SchoolFriend2
Q46Metatthemarket2
Q46Huntedtogether2
Q46Friend2
Q46Wereatthechurch2
Q46OtherInteraction2
Q47Otherinformationaboutthecontact2
Q48Contactperson3Nname
Q49ContactPerson3Relationship
Q50DateContactPerson3
Q51Familycontact3
Q50Preparedfoodtogether3
Q51Sharedabed3
Q51Tookcareofthissickperson3
Q51SchoolFriend3
Q51Metatthemarket3
Q51Huntedtogether3
Q51Friend3
Q51Wereatthechurch3
Q51OtherInteraction3
Q52Otherinformationaboutthecontact3
Q53Contactperson4Nname
Q54ContactPerson4Relationship
Q55DateContactPerson4
Q56Familycontac4
Q56Preparedfoodtogether
Q56Sharedabed4
Q56Tookcareofthissickperson4
Q56SchoolFriend4
Q56Metatthemarket4
Q56Huntedtogether4
Q56Friend4
Q56Wereatthechurch4
Q56OtherInteraction4
Q57Otherinformationaboutthecontact21
suspcases

**Comment by hzi-braunschweig** [comment]
We could imagine how many variables per disease we would have, What would be the best way forward. Can we import disease specific variables as is in the db, they would format their excel sheet to be as the template we give and  import. I think this is the best idea. We have to pre-select some standardized variables like LGA name, to import where neccessary

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] add import button to cases directory that opens an import dialog
- [ ] import dialog gives a short manual on how to format data and a template on how the data should be formatted (and reference to data dictionary)
- [ ] use vaadin upload receiver https://vaadin.com/docs/v7/framework/components/components-upload.html
- [ ] import will go though line by line and call saveCase for every entry
- [ ] imported entities: Case, Person, Location, Symptoms, Hospitalization - if it's "free" also epi data. NOT lists (e.g. previous hospitalizations, contacts, burials, etc.)

Generation of the template file

- [ ] generate a temp csv file
- [ ] create a temporary case
- [ ] go per reflection through all properties and write their names as columns (use ; seperator)
- [ ] for child entities do the same recursive passing the parent-path (e.g. "person.address")
- [ ] sort out property types that aren't supported (lists)
- [ ] call this from a stream resource

Import step by step

- [ ] parse first line and create dictionary of column paths. Split hierarchie paths into the elements (e.g. "person.address.address") -> List<String[]> where each element of the list is the complete path (some of the arrays will only have one element, e.g. "disease")
- [ ] for each line create a new case entity using the backend create case method; reporting user is the currently importing user
- [ ] for each column use reflection to identify the property / sub property - call setter for last array element and getter for previous ones
- [ ] cell value: 
  - String: no parsing
  - Enum: Parse using valueOf
  - Date: parse using custom dateformatter based on example data
  - Double/Float/Integer: parse using according class
  - specific reference entities (Region, District, Community, Facility, User): parse using getByName
- [ ] after "successful" import provide the failed imports file as download

Possible import problems:

1. csv column does not exist in entity -> cancel the whole process and throw exception to inform the user about an unknow column
2. value in cell is not compatible (e.g. enum valueOf does not work or date cannot be parsed) OR reference value in cell does not exist (e.g. region, district, user). Cancel import of the single case. The complete line is written to an "failedImports.csv" file. As last column add the error message
3. saving fails (e.g. due to NotNull constrains): Also write to complete case line to the failed imports and add the error message

The import will currently not look for duplicates!

@hzi-braunschweig 
- [ ] provide example data - at least 50 cases with pseudonymized cases (name, birthdate, etc.). Please send this to Maté via email

**Comment by MateStrysewskeSym** [comment]
- [ ] make sure that info dialogs stay open longer

**Comment by MateStrysewskeSym** [comment]
- [ ] create constant with temp file prefix ("sormas") in ImportExportFacade and use it in cron service and all fields/constants that use it
- [ ] use correct logger class
- [ ] build custom import error exception in exception constructor, remove value and columnName fields, remove customMessage and use normal exception message instead
- [ ] add comment why we're using save method from facade (to make sure that automatisms are executed)
- [ ] save person through personFacade, remove ensurePersisted calls for epi data, hospitalization and symptoms
- [ ] split code into ImportFacade and ExportFacade (use same package)
- [ ] remove sourceView from stream resource
- [ ] move infrastructure checks to save method
