### ISSUE TITLE
"Case table" and "contact table" export variables

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Open#572]
Please find attached, the nominated variables to be seen on front-end "case table" export. 
The entire database export under statistics is still fine and very necessary (as requested by NCDC ICC).
[SORMAS_Variables_Export.4.19.2018.xlsx](https://github.com/hzi-braunschweig/SORMAS-Open/files/1928505/SORMAS_Variables_Export.4.19.2018.xlsx)

**Comment by hzi-braunschweig** [comment]
![image](https://user-images.githubusercontent.com/19344651/38998029-09b82420-43ef-11e8-8b8f-8d1ac2ebe7f4.png)
@MartinWahnschaffeSymeda @MateStrysewskeSym

**Comment by MartinWahnschaffeSymeda** [comment]
Cases:

* What if there are multiple samples for a case. Should will list the dates and results in the associated column using a comma as seperator?
* How should travel history be formatted? Is this just free text?
* Do we have fields for "date of   commencement of ribavarin" and "date of commencement of treatment"?

Contacts:

* There is no sample collection for a contact. Only when it has become a case. How should we deal with this?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @Chinedar 
- [ ] What if there are multiple samples for a case. Should will list the dates and results in the associated column using a comma as seperator?
I think we should list the dates and results in the associated column using a comma @Chinedar please confirm this

- [ ] How should travel history be formatted? Is this just free text?
@Chinedar you guys left the travel history blank so we will assume that it is free text except you define otherwise.

- [ ] Do we have fields for "date of commencement of ribavarin" and "date of commencement of treatment"?

@Chinedar Please address this issues...


Contacts:

- [ ] There is no sample collection for a contact. Only when it has become a case. How should we deal with this?

This should be taken out. It does not apply.

**Comment by Chinedar** [comment]
Cases:

   - What if there are multiple samples for a case. Should will list the
   dates and results in the associated column using a comma as seperator? - I
   agree to list all and separate with comma.
   - How should travel history be formatted? Is this just free text? - in
   this case we can bring in the data points/variables in SORMAS: "visited a
   burial", "visited a social event", "travelled"
   - Do we have fields for "date of commencement of ribavarin" and "date of
   commencement of treatment"? - Let's replace this with "admitted to
   health facility" and "date of visit or admission"

Contacts:

   - There is no sample collection for a contact. Only when it has become a
   case. How should we deal with this? - This should be removed please.
   Their is no such variable in SORMAS for contacts.

Thanks.

**Comment by MartinWahnschaffeSymeda** [comment]
Implementation idea:

- [ ] build CaseExtendedDto with the additional fields needed (e.g. representation of all symptoms, travel infos, etc.)
- [ ] backend uses case entity to fill the extended dto
- [ ] extended dto can be retrieved for a list of case ids. This could also be done chunk wise during download streaming.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] textfields for other symptoms are included into export although empty
