### ISSUE TITLE
Hospitalization data in webapp [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#89]
@stoikkanen I think we have to separate hospitalization data from epidemiological data more clearly. The data dictionary currently mixes them: https://docs.google.com/spreadsheets/d/1BA_RjM-ZhxFrzpAJdv0UVGhicHXNP6JnPBA-xzdrQKs/edit?pli=1#gid=370159711

* I think lines 7 to 21 belong to the hospitalization data. 
* Lines 22 to 68 are epidemiologic.
* What about lines 2 to 6?
* Do we need fields to enter hospitalizations **before** the illness in the epidemiologic section? (compare https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a3ac2d54d and https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a7613be44)

- [x] Issues for epi data and mobile app

**Comment by MartinWahnschaffeSymeda** [comment]
@stoikkanen please have a look at my question on this issue

**Comment by stoikkanen** [comment]
@MartinWahnschaffeSymeda 
Hi, I do not see a big discrepancy there? The  lines 7-21 are linked to hospitalisations (current and past) linked to the current illness. Hospitalisations could be asked first, before other information since it is important for the case finding and the state where hospital informant starts.  
Lines 2-6 are epidemiologic and could be moved after hospitalisations.

In the moqups https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a3ac2d54d the question about hospitalisation is about hospitalisations before this illness and thus epidemiological in nature and related to the potential exposure in a hospital.  I added few rows to the end to cover this in the  data dictionary. This is however what we already earlier discussed about: we had in the earlier version questions about contacts to other sick people included but they were moved away since the contact questions. However, I think is still good to ask this separately since contacts like this might be forgotten otherwise.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] refine data dictionary: hospitalization data is part of new Hospitalization entity (measles vaccination and pregnancy stay in case)
- [ ] update hospitalization moqup (https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a7613be44)
- [ ] update case data moqup (https://app.moqups.com/symeda/3NUENEwuOE/edit/page/afc481082)
- [ ] create hospitalization entity; update case entity
- [ ] HospitalizationDto (including health facility), Facade, Service
- [ ] ui view

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym 
In order to be able to create the list field I have added a PreviousHospitalizationDto and put a list of it into the CaseDataDto. This needs to be moved to the HospitalizationDataDto later.
The PreviousHospitalizationsField gives an example of how to use this in the UI form.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] health facility should only be a label (not a read only field)
